# Site settings
title: My Projects
description: Welcome to my portfolio! Here are some of the projects I've worked on.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paulosuma.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Author settings
author:
  name: Your Name
  email: your-email@example.com
  github: yourusername

# Social media links (optional)
social:
  twitter: yourusername
  github: yourusername
  linkedin: yourusername

# Navigation links
navigation:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about"
  - name: "Projects"
    url: "/projects"
  - name: "Contact"
    url: "/contact"

# Custom variables (optional)
custom:
  highlight_color: "#4CAF50"
  show_footer: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# Markdown processing
kramdown:
  input: GFM
  hard_wrap: false
